# Generated by Django 4.2.6 on 2023-10-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nit', models.BigIntegerField()),
                ('Dv', models.SmallIntegerField()),
                ('RazonSocial', models.CharField(max_length=150)),
                ('TipoEntidad', models.SmallIntegerField()),
                ('CodigoSuper', models.SmallIntegerField()),
                ('Sigla', models.CharField(max_length=60)),
                ('Descripcion', models.CharField(max_length=60)),
                ('Departamento', models.CharField(max_length=30)),
                ('Ciudad', models.CharField(max_length=30)),
                ('Direccion', models.CharField(max_length=60)),
                ('Telefono', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=60)),
                ('CIIU', models.SmallIntegerField()),
                ('RepresentanteLegal', models.CharField(max_length=60)),
                ('Gremio', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'entidad',
                'ordering': ['-created_at'],
            },
        ),
    ]
